---
title: "Kaitlyn Fu"
subtitle: kaitlyn_fu@ucsb.edu
---

# Education 
University of California, Santa Barbara — Geography B.A., Global Studies B.A. 

# Experiences 
- San Francisco International Airport, Revenue Development and Management Intern
  - Gained knowledge of property management, airport tenant lease compliances, and business opportunities at SFO. 
  - Validated the build-out cost balances provided by the tenants. 
  - Supported the Revenue Development and Management team in the grand opening of the Harvey Milk Terminal.

- Taiwanese American Student Association, Treasurer
  - Oversaw fundraising goals and presented proposals to various institutions for funding. 
  - Advised executive board regarding significant expenditures to keep projects in line with budget limitations. 
  -Planned and managed $5000 annual budgets by tracking expenses and profits to maintain favorable balance. 

- County of Santa Barbara, Real Property Division Intern
  - Calculated and fact-checked the logistics of the properties from the floor plans to what is recorded in the database. 
  - Facilitated communication between other interns and supervisor on challenges and updates.
  - Learned how rent pricing is determined for County’s properties. 

# Languages 
- Fluent in English and Burmese 

- Beginner proficency in Chinese and Italian

